spring:
  application:
    name: registry-server
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.MetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.export.simple.SimpleMetricsExportAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.web.tomcat.TomcatMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration

server:
  port: 8762

eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: registry-server
    preferIpAddress: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# Configuración de actuator simplificada
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
  metrics:
    enable:
      all: false
      system: false
      process: false
      jvm: false
  health:
    defaults:
      enabled: false
    diskspace:
      enabled: false